default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: lucas
  password: 12345678
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: SGP_development

production:
  <<: *default
  database: SGP_production